name       : tap-plugins
version    : 1.0.1
release    : 2
source     :
    - git|https://github.com/tomszilagyi/tap-plugins.git : v1.0.1
license    : GPL-2.0
component  : multimedia.library
summary    : A set of LADSPA plugins
description: |
    Tom's Audio Processing plugins is a selection of LADSPA plugins for audio engineering on the Linux platform. Intended for use in a professional DAW environment such as Ardour, it includes high quality reverberation, echo, eq, limiter & more
build      : |
    sed -i 's|/usr/local/|$(installdir)/usr/|' Makefile
    sed -i 's|lib|lib64|' Makefile
    %make
install    : |
    %make_install
