name       : tap-plugins
version    : 0.7.3
release    : 1
source     :
    - https://freefr.dl.sourceforge.net/project/tap-plugins/tap-plugins/0.7.3/tap-plugins-0.7.3.tar.gz : 23ff6b7f5e0968c6afa77bbf3dce74841c1de4a3badfcfad6ccc4c27665b7c2e
license    : GPL-2.0
component  : multimedia.library
summary    : A set of LADSPA plugins
description: |
    Tom's Audio Processing plugins is a selection of LADSPA plugins for audio engineering on the Linux platform. Intended for use in a professional DAW environment such as Ardour, it includes high quality reverberation, echo, eq, limiter & more
build      : |
    sed -i 's|/usr/local/|$(installdir)/usr/|' Makefile
    sed -i 's|lib|lib64|' Makefile
    %make
install    : |
    %make_install
